{% set name = "screeninfo" %}
{% set version = "0.8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/screeninfo-{{ version }}.tar.gz
  sha256: 9983076bcc7e34402a1a9e4d7dabf3729411fd2abb3f3b4be7eba73519cd2ed1

build:
  number: 1
  skip: true  # [python_impl == 'pypy']
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python
    - pip
    - poetry
  host:
    - pip
    - python
    - poetry
  run:
    - python
    - poetry
    - cython  # [osx]
    - pyobjc-framework-cocoa  # [osx]

test:
  imports:
    - screeninfo
    - screeninfo.enumerators
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rr-/screeninfo
  summary: Fetch location and size of physical screens.
  license: MIT AND BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - gauranshkumar
