{% set name = "screeninfo" %}
{% set version = "0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/screeninfo-{{ version }}.tar.gz
  sha256: 9501bf8b8458c7d1be4cb0ac9abddddfa80b932fb3f65bfcb54f5586434b1dc5

build:
  number: 2
  skip: true  # [python_impl == 'pypy']
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python
    - pip
    - poetry
  host:
    - pip
    - python
    - poetry
  run:
    - python
    - poetry

test:
  imports:
    - screeninfo
    - screeninfo.enumerators
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rr-/screeninfo
  summary: Fetch location and size of physical screens.
  license: MIT AND BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - gauranshkumar
