{% set name = "screeninfo" %}
{% set version = "0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/screeninfo-{{ version }}.tar.gz
  sha256: 9501bf8b8458c7d1be4cb0ac9abddddfa80b932fb3f65bfcb54f5586434b1dc5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - dataclasses  # [py<37]
    - pyobjc-framework-cocoa  # [osx]
    - python
    - cython  # [osx]

test:
  imports:
    - screeninfo
    - screeninfo.enumerators

about:
  home: https://github.com/rr-/screeninfo
  summary: Fetch location and size of physical screens.
  license: MIT AND BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - gauranshkumar
